// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type ProhibitedPattern struct {
	ID          int64  `json:"id"`
	SessionID   string `json:"session_id"`
	PatternType string `json:"pattern_type"`
	Pattern     string `json:"pattern"`
}

type Session struct {
	ID                  string         `json:"id"`
	DisplayName         string         `json:"display_name"`
	AdminName           string         `json:"admin_name"`
	AdminPasswordHash   string         `json:"admin_password_hash"`
	FriendAccessKey     string         `json:"friend_access_key"`
	SpotifyPlaylistID   sql.NullString `json:"spotify_playlist_id"`
	SongDurationLimitMs sql.NullInt64  `json:"song_duration_limit_ms"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
	SpotifyPlaylistName sql.NullString `json:"spotify_playlist_name"`
	MusicService        string         `json:"music_service"`
}

type SongRequest struct {
	ID              int64          `json:"id"`
	SessionID       string         `json:"session_id"`
	ExternalTrackID string         `json:"external_track_id"`
	TrackName       string         `json:"track_name"`
	ArtistNames     string         `json:"artist_names"`
	AlbumName       string         `json:"album_name"`
	AlbumArtUrl     sql.NullString `json:"album_art_url"`
	DurationMs      int64          `json:"duration_ms"`
	ExternalUri     string         `json:"external_uri"`
	Status          string         `json:"status"`
	RequestedAt     sql.NullTime   `json:"requested_at"`
	ProcessedAt     sql.NullTime   `json:"processed_at"`
	RejectionReason sql.NullString `json:"rejection_reason"`
	RequesterName   sql.NullString `json:"requester_name"`
}
