// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prohibited_patterns.sql

package db

import (
	"context"
)

const createProhibitedPattern = `-- name: CreateProhibitedPattern :one
INSERT INTO prohibited_patterns (session_id, pattern_type, pattern)
VALUES (?, ?, ?)
RETURNING id, session_id, pattern_type, pattern
`

type CreateProhibitedPatternParams struct {
	SessionID   string `json:"session_id"`
	PatternType string `json:"pattern_type"`
	Pattern     string `json:"pattern"`
}

func (q *Queries) CreateProhibitedPattern(ctx context.Context, arg CreateProhibitedPatternParams) (ProhibitedPattern, error) {
	row := q.db.QueryRowContext(ctx, createProhibitedPattern, arg.SessionID, arg.PatternType, arg.Pattern)
	var i ProhibitedPattern
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.PatternType,
		&i.Pattern,
	)
	return i, err
}

const deleteProhibitedPattern = `-- name: DeleteProhibitedPattern :exec
DELETE FROM prohibited_patterns WHERE id = ?
`

func (q *Queries) DeleteProhibitedPattern(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProhibitedPattern, id)
	return err
}

const deleteProhibitedPatternsBySessionID = `-- name: DeleteProhibitedPatternsBySessionID :exec
DELETE FROM prohibited_patterns WHERE session_id = ?
`

func (q *Queries) DeleteProhibitedPatternsBySessionID(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteProhibitedPatternsBySessionID, sessionID)
	return err
}

const getProhibitedPatternsBySessionID = `-- name: GetProhibitedPatternsBySessionID :many
SELECT id, session_id, pattern_type, pattern FROM prohibited_patterns WHERE session_id = ?
`

func (q *Queries) GetProhibitedPatternsBySessionID(ctx context.Context, sessionID string) ([]ProhibitedPattern, error) {
	rows, err := q.db.QueryContext(ctx, getProhibitedPatternsBySessionID, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProhibitedPattern
	for rows.Next() {
		var i ProhibitedPattern
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.PatternType,
			&i.Pattern,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
