// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	ApproveSongRequest(ctx context.Context, id int64) error
	ClearLoungeCredentials(ctx context.Context, id string) error
	CreateProhibitedPattern(ctx context.Context, arg CreateProhibitedPatternParams) (ProhibitedPattern, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSongRequest(ctx context.Context, arg CreateSongRequestParams) (SongRequest, error)
	DeleteAllSongRequestsBySessionID(ctx context.Context, sessionID string) error
	DeleteProhibitedPattern(ctx context.Context, id int64) error
	DeleteProhibitedPatternsBySessionID(ctx context.Context, sessionID string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSongRequest(ctx context.Context, id int64) error
	FriendKeyExists(ctx context.Context, friendAccessKey string) (int64, error)
	GetLoungeCredentials(ctx context.Context, id string) (GetLoungeCredentialsRow, error)
	GetPendingSongRequests(ctx context.Context, sessionID string) ([]SongRequest, error)
	GetProhibitedPatternsBySessionID(ctx context.Context, sessionID string) ([]ProhibitedPattern, error)
	GetSessionByAdminCredentials(ctx context.Context, arg GetSessionByAdminCredentialsParams) (Session, error)
	GetSessionByFriendKey(ctx context.Context, friendAccessKey string) (Session, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetSongRequestByID(ctx context.Context, id int64) (SongRequest, error)
	GetSongRequestsBySessionID(ctx context.Context, sessionID string) ([]SongRequest, error)
	IsDuplicateRequest(ctx context.Context, arg IsDuplicateRequestParams) (int64, error)
	ListAllSessions(ctx context.Context) ([]Session, error)
	RejectSongRequest(ctx context.Context, arg RejectSongRequestParams) error
	SaveLoungeCredentials(ctx context.Context, arg SaveLoungeCredentialsParams) error
	UpdateSessionPlaylist(ctx context.Context, arg UpdateSessionPlaylistParams) error
	UpdateSessionSettings(ctx context.Context, arg UpdateSessionSettingsParams) error
}

var _ Querier = (*Queries)(nil)
