// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const clearLoungeCredentials = `-- name: ClearLoungeCredentials :exec
UPDATE sessions SET lounge_screen_id = NULL, lounge_token = NULL, lounge_screen_name = NULL, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) ClearLoungeCredentials(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, clearLoungeCredentials, id)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, display_name, admin_name, admin_password_hash, friend_access_key, spotify_playlist_id, song_duration_limit_ms, music_service)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, display_name, admin_name, admin_password_hash, friend_access_key, spotify_playlist_id, song_duration_limit_ms, created_at, updated_at, spotify_playlist_name, music_service, lounge_screen_id, lounge_token, lounge_screen_name
`

type CreateSessionParams struct {
	ID                  string         `json:"id"`
	DisplayName         string         `json:"display_name"`
	AdminName           string         `json:"admin_name"`
	AdminPasswordHash   string         `json:"admin_password_hash"`
	FriendAccessKey     string         `json:"friend_access_key"`
	SpotifyPlaylistID   sql.NullString `json:"spotify_playlist_id"`
	SongDurationLimitMs sql.NullInt64  `json:"song_duration_limit_ms"`
	MusicService        string         `json:"music_service"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.DisplayName,
		arg.AdminName,
		arg.AdminPasswordHash,
		arg.FriendAccessKey,
		arg.SpotifyPlaylistID,
		arg.SongDurationLimitMs,
		arg.MusicService,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AdminName,
		&i.AdminPasswordHash,
		&i.FriendAccessKey,
		&i.SpotifyPlaylistID,
		&i.SongDurationLimitMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SpotifyPlaylistName,
		&i.MusicService,
		&i.LoungeScreenID,
		&i.LoungeToken,
		&i.LoungeScreenName,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const friendKeyExists = `-- name: FriendKeyExists :one
SELECT EXISTS(SELECT 1 FROM sessions WHERE friend_access_key = ?) AS exists_flag
`

func (q *Queries) FriendKeyExists(ctx context.Context, friendAccessKey string) (int64, error) {
	row := q.db.QueryRowContext(ctx, friendKeyExists, friendAccessKey)
	var exists_flag int64
	err := row.Scan(&exists_flag)
	return exists_flag, err
}

const getLoungeCredentials = `-- name: GetLoungeCredentials :one
SELECT lounge_screen_id, lounge_token, lounge_screen_name FROM sessions WHERE id = ?
`

type GetLoungeCredentialsRow struct {
	LoungeScreenID   sql.NullString `json:"lounge_screen_id"`
	LoungeToken      sql.NullString `json:"lounge_token"`
	LoungeScreenName sql.NullString `json:"lounge_screen_name"`
}

func (q *Queries) GetLoungeCredentials(ctx context.Context, id string) (GetLoungeCredentialsRow, error) {
	row := q.db.QueryRowContext(ctx, getLoungeCredentials, id)
	var i GetLoungeCredentialsRow
	err := row.Scan(&i.LoungeScreenID, &i.LoungeToken, &i.LoungeScreenName)
	return i, err
}

const getSessionByAdminCredentials = `-- name: GetSessionByAdminCredentials :one
SELECT id, display_name, admin_name, admin_password_hash, friend_access_key, spotify_playlist_id, song_duration_limit_ms, created_at, updated_at, spotify_playlist_name, music_service, lounge_screen_id, lounge_token, lounge_screen_name FROM sessions WHERE admin_name = ? AND admin_password_hash = ?
`

type GetSessionByAdminCredentialsParams struct {
	AdminName         string `json:"admin_name"`
	AdminPasswordHash string `json:"admin_password_hash"`
}

func (q *Queries) GetSessionByAdminCredentials(ctx context.Context, arg GetSessionByAdminCredentialsParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByAdminCredentials, arg.AdminName, arg.AdminPasswordHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AdminName,
		&i.AdminPasswordHash,
		&i.FriendAccessKey,
		&i.SpotifyPlaylistID,
		&i.SongDurationLimitMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SpotifyPlaylistName,
		&i.MusicService,
		&i.LoungeScreenID,
		&i.LoungeToken,
		&i.LoungeScreenName,
	)
	return i, err
}

const getSessionByFriendKey = `-- name: GetSessionByFriendKey :one
SELECT id, display_name, admin_name, admin_password_hash, friend_access_key, spotify_playlist_id, song_duration_limit_ms, created_at, updated_at, spotify_playlist_name, music_service, lounge_screen_id, lounge_token, lounge_screen_name FROM sessions WHERE friend_access_key = ?
`

func (q *Queries) GetSessionByFriendKey(ctx context.Context, friendAccessKey string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByFriendKey, friendAccessKey)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AdminName,
		&i.AdminPasswordHash,
		&i.FriendAccessKey,
		&i.SpotifyPlaylistID,
		&i.SongDurationLimitMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SpotifyPlaylistName,
		&i.MusicService,
		&i.LoungeScreenID,
		&i.LoungeToken,
		&i.LoungeScreenName,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, display_name, admin_name, admin_password_hash, friend_access_key, spotify_playlist_id, song_duration_limit_ms, created_at, updated_at, spotify_playlist_name, music_service, lounge_screen_id, lounge_token, lounge_screen_name FROM sessions WHERE id = ?
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AdminName,
		&i.AdminPasswordHash,
		&i.FriendAccessKey,
		&i.SpotifyPlaylistID,
		&i.SongDurationLimitMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SpotifyPlaylistName,
		&i.MusicService,
		&i.LoungeScreenID,
		&i.LoungeToken,
		&i.LoungeScreenName,
	)
	return i, err
}

const listAllSessions = `-- name: ListAllSessions :many
SELECT id, display_name, admin_name, admin_password_hash, friend_access_key, spotify_playlist_id, song_duration_limit_ms, created_at, updated_at, spotify_playlist_name, music_service, lounge_screen_id, lounge_token, lounge_screen_name FROM sessions
`

func (q *Queries) ListAllSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listAllSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AdminName,
			&i.AdminPasswordHash,
			&i.FriendAccessKey,
			&i.SpotifyPlaylistID,
			&i.SongDurationLimitMs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SpotifyPlaylistName,
			&i.MusicService,
			&i.LoungeScreenID,
			&i.LoungeToken,
			&i.LoungeScreenName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveLoungeCredentials = `-- name: SaveLoungeCredentials :exec
UPDATE sessions SET lounge_screen_id = ?, lounge_token = ?, lounge_screen_name = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type SaveLoungeCredentialsParams struct {
	LoungeScreenID   sql.NullString `json:"lounge_screen_id"`
	LoungeToken      sql.NullString `json:"lounge_token"`
	LoungeScreenName sql.NullString `json:"lounge_screen_name"`
	ID               string         `json:"id"`
}

func (q *Queries) SaveLoungeCredentials(ctx context.Context, arg SaveLoungeCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, saveLoungeCredentials,
		arg.LoungeScreenID,
		arg.LoungeToken,
		arg.LoungeScreenName,
		arg.ID,
	)
	return err
}

const updateSessionPlaylist = `-- name: UpdateSessionPlaylist :exec
UPDATE sessions SET spotify_playlist_id = ?, spotify_playlist_name = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateSessionPlaylistParams struct {
	SpotifyPlaylistID   sql.NullString `json:"spotify_playlist_id"`
	SpotifyPlaylistName sql.NullString `json:"spotify_playlist_name"`
	ID                  string         `json:"id"`
}

func (q *Queries) UpdateSessionPlaylist(ctx context.Context, arg UpdateSessionPlaylistParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionPlaylist, arg.SpotifyPlaylistID, arg.SpotifyPlaylistName, arg.ID)
	return err
}

const updateSessionSettings = `-- name: UpdateSessionSettings :exec
UPDATE sessions SET song_duration_limit_ms = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateSessionSettingsParams struct {
	SongDurationLimitMs sql.NullInt64 `json:"song_duration_limit_ms"`
	ID                  string        `json:"id"`
}

func (q *Queries) UpdateSessionSettings(ctx context.Context, arg UpdateSessionSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionSettings, arg.SongDurationLimitMs, arg.ID)
	return err
}
